apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: monitoring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-app
          image: prom/pushgateway
          ports:
            - containerPort: 9091
