apiVersion: v1
kind: Service
metadata:
  name: example-app-service
  namespace: monitoring-app
spec:
  selector:
    app: example-app
  ports:
    - port: 9091
      targetPort: 9091
  type: NodePort
