apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'example-app'
        static_configs:
          - targets: ['example-app-service.monitoring-app.svc.cluster.local:9091']
